import { useState, useMemo } from 'react'
import { Driver, DriverPerformance, Anomaly, StoredInterviewRecord, AnomalyType } from '../types'
import { ANOMALY_LABELS, ANOMALY_COLORS } from '../data/mockData'

interface InterviewModalProps {
  driver: Driver
  performance: DriverPerformance
  selectedAnomalyIds: Set<string>
  onSelectedChange: (ids: Set<string>) => void
  weekStart: string
  onClose: () => void
  fleetName?: string
  routeName?: string
  weekEnd?: string
  onSave?: (record: StoredInterviewRecord) => void
}

const ANOMALY_ICONS: Record<string, string> = {
  early_arrival: '⏰',
  late_arrival: '⏱️',
  route_deviation: '🗺️',
  sudden_brake: '🛑',
  sudden_turn: '↩️',
  gps_blank: '📡',
  overspeed: '⚡'
}

const DEFAULT_REQUIREMENTS: Record<string, string> = {
  early_arrival: '严格遵守到站时间，禁止提前到站导致学生候车时间不足；如遇特殊情况提前需提前报备调度。',
  late_arrival: '合理规划发车时间与行驶速度，确保准点到站；连续迟到将影响当月绩效。',
  route_deviation: '严格按照规划线路行驶，不得擅自改道；如遇道路施工等特殊情况需先报备调度。',
  sudden_brake: '保持安全车距，提前预判路况，平稳驾驶，避免紧急制动。',
  sudden_turn: '通过路口和弯道提前减速，匀速通过，避免急转弯。',
  gps_blank: '每日出车前检查GPS设备是否正常工作，发现异常立即报修。',
  overspeed: '严格遵守限速规定，特别是经过学校、居民区路段必须减速。'
}

function InterviewModal({ driver, performance, selectedAnomalyIds, onSelectedChange, weekStart, onClose, fleetName = '', routeName, weekEnd: weekEndProp, onSave }: InterviewModalProps) {
  const [improvementRequirements, setImprovementRequirements] = useState('')
  const [notes, setNotes] = useState('')
  const [nextReviewDate, setNextReviewDate] = useState(() => {
    const d = new Date()
    d.setDate(d.getDate() + 14)
    return d.toISOString().split('T')[0]
  })
  const [supervisor, setSupervisor] = useState('王主管')
  const [showGenerated, setShowGenerated] = useState(false)

  const route = routeName ? { name: routeName } : null
  const weekEnd = weekEndProp || performance.weekEnd

  const selectedAnomalies: Anomaly[] = useMemo(() => {
    return performance.anomalies.filter(a => selectedAnomalyIds.has(a.id))
  }, [performance.anomalies, selectedAnomalyIds])

  const autoGeneratedRequirements = useMemo(() => {
    const types = new Set(selectedAnomalies.map(a => a.type))
    return Array.from(types)
      .map(t => DEFAULT_REQUIREMENTS[t])
      .filter(Boolean)
      .join('\n\n')
  }, [selectedAnomalies])

  const toggleSelect = (id: string) => {
    const next = new Set(selectedAnomalyIds)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    onSelectedChange(next)
  }

  const toggleSelectAll = () => {
    if (selectedAnomalyIds.size === performance.anomalies.length) {
      onSelectedChange(new Set())
    } else {
      onSelectedChange(new Set(performance.anomalies.map(a => a.id)))
    }
  }

  const selectHighSeverity = () => {
    onSelectedChange(new Set(performance.anomalies.filter(a => a.severity === 'high').map(a => a.id)))
  }

  const fillAutoRequirements = () => {
    setImprovementRequirements(autoGeneratedRequirements)
  }

  const handleGenerate = () => {
    setShowGenerated(true)
  }

  const handleSaveAndClose = () => {
    if (onSave) {
      const anomalySummaries = Array.from(
        selectedAnomalies.reduce((map, a) => {
          map.set(a.type, (map.get(a.type) || 0) + 1)
          return map
        }, new Map<string, number>())
      ).map(([type, count]) => ({ type: type as AnomalyType, count }))

      const record: StoredInterviewRecord = {
        id: `iv_${Date.now()}_${Math.floor(Math.random() * 10000)}`,
        interviewDate,
        nextReviewDate,
        supervisor,
        notes,
        improvementRequirements,
        selectedAnomalyIds: Array.from(selectedAnomalyIds),
        driverId: driver.id,
        driverName: driver.name,
        driverEmployeeId: driver.employeeId,
        driverPhone: driver.phone,
        fleetId: driver.fleetId,
        fleetName,
        routeId: driver.routeId,
        routeName: route?.name || '',
        weekStart,
        weekEnd,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        anomalySummaries,
        anomalyDetails: selectedAnomalies.map(a => ({
          id: a.id,
          type: a.type,
          severity: a.severity,
          date: a.date,
          time: a.time,
          locationName: a.locationName,
          description: a.description
        }))
      }
      onSave(record)
    }
    onClose()
  }

  const handlePrint = () => {
    window.print()
  }

  const interviewDate = new Date().toISOString().split('T')[0]

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()} style={{ width: showGenerated ? 820 : 720 }}>
        <div className="modal-header">
          <div>
            <div className="modal-title">
              {showGenerated ? '📋 司机面谈记录' : '📝 生成司机面谈记录'}
            </div>
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4 }}>
              {driver.name} · {driver.employeeId} · {route?.name}
            </div>
          </div>
          <button className="modal-close" onClick={onClose}>✕</button>
        </div>

        <div className="modal-body">
          {!showGenerated ? (
            <>
              <div className="summary-grid">
                <div className="summary-item">
                  <div className="summary-label">本周准点率</div>
                  <div className="summary-value">
                    {performance.onTimeRate}<span className="sub">%</span>
                  </div>
                </div>
                <div className="summary-item">
                  <div className="summary-label">异常事件总数</div>
                  <div className="summary-value">
                    {performance.anomalies.length}<span className="sub">起</span>
                  </div>
                </div>
                <div className="summary-item">
                  <div className="summary-label">高危事件</div>
                  <div className="summary-value">
                    {performance.anomalies.filter(a => a.severity === 'high').length}
                    <span className="sub">起</span>
                  </div>
                </div>
                <div className="summary-item">
                  <div className="summary-label">已选择问题</div>
                  <div className="summary-value" style={{ color: 'var(--accent)' }}>
                    {selectedAnomalyIds.size}<span className="sub">项</span>
                  </div>
                </div>
              </div>

              <div className="form-group">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                  <label className="form-label">需培训的问题项</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <button className="filter-chip" onClick={selectHighSeverity}>
                      选中高危
                    </button>
                    <button className="filter-chip" onClick={toggleSelectAll}>
                      {selectedAnomalyIds.size === performance.anomalies.length ? '取消全选' : '全选'}
                    </button>
                  </div>
                </div>
                <div className="selected-anomalies-list">
                  {performance.anomalies.length === 0 ? (
                    <div style={{ padding: 20, textAlign: 'center', color: 'var(--text-muted)' }}>
                      ✅ 本周无异常记录
                    </div>
                  ) : (
                    performance.anomalies.map(a => (
                      <div
                        key={a.id}
                        className="selected-anomaly-item"
                        onClick={() => toggleSelect(a.id)}
                        style={{
                          background: selectedAnomalyIds.has(a.id) ? 'rgba(59, 130, 246, 0.08)' : 'transparent',
                          border: selectedAnomalyIds.has(a.id) ? '1px solid var(--accent)' : '1px solid transparent'
                        }}
                      >
                        <div
                          className={`anomaly-checkbox ${selectedAnomalyIds.has(a.id) ? 'checked' : ''}`}
                          style={{ flexShrink: 0 }}
                        >
                          {selectedAnomalyIds.has(a.id) && '✓'}
                        </div>
                        <div
                          className="anomaly-type-icon"
                          style={{
                            background: `${ANOMALY_COLORS[a.type]}25`,
                            color: ANOMALY_COLORS[a.type],
                            flexShrink: 0
                          }}
                        >
                          {ANOMALY_ICONS[a.type]}
                        </div>
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{ fontSize: 13, fontWeight: 500, color: ANOMALY_COLORS[a.type] }}>
                            {ANOMALY_LABELS[a.type]}
                            <span style={{ marginLeft: 8, fontSize: 10 }} className={`badge ${a.severity === 'high' ? 'badge-red' : a.severity === 'medium' ? 'badge-yellow' : 'badge-gray'}`}>
                              {a.severity === 'high' ? '高危' : a.severity === 'medium' ? '中危' : '低危'}
                            </span>
                          </div>
                          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 3 }}>
                            {a.date} · {a.time} · {a.locationName}
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label className="form-label">面谈日期</label>
                  <input
                    type="date"
                    className="form-input"
                    value={interviewDate}
                    disabled
                    style={{ opacity: 0.7 }}
                  />
                </div>
                <div className="form-group">
                  <label className="form-label">下次观察日期</label>
                  <input
                    type="date"
                    className="form-input"
                    value={nextReviewDate}
                    onChange={e => setNextReviewDate(e.target.value)}
                  />
                </div>
              </div>

              <div className="form-group">
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                  <label className="form-label">改进要求</label>
                  <button
                    className="filter-chip"
                    onClick={fillAutoRequirements}
                    disabled={selectedAnomalies.length === 0}
                    style={selectedAnomalies.length === 0 ? { opacity: 0.5, cursor: 'not-allowed' } : {}}
                  >
                    ✨ 一键生成建议
                  </button>
                </div>
                <textarea
                  className="form-textarea"
                  placeholder="请输入具体的改进要求..."
                  value={improvementRequirements}
                  onChange={e => setImprovementRequirements(e.target.value)}
                />
              </div>

              <div className="form-group">
                <label className="form-label">主管备注</label>
                <textarea
                  className="form-textarea"
                  placeholder="记录面谈过程中的其他补充信息..."
                  value={notes}
                  onChange={e => setNotes(e.target.value)}
                  style={{ minHeight: 80 }}
                />
              </div>

              <div className="form-group">
                <label className="form-label">面谈主管</label>
                <input
                  type="text"
                  className="form-input"
                  value={supervisor}
                  onChange={e => setSupervisor(e.target.value)}
                />
              </div>
            </>
          ) : (
            <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border)', borderRadius: 12, padding: 28 }}>
              <div style={{ textAlign: 'center', marginBottom: 24, paddingBottom: 20, borderBottom: '1px solid var(--border)' }}>
                <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 6 }}>校车司机面谈记录表</div>
                <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>School Bus Driver Interview Record</div>
                <div style={{ fontSize: 13, color: 'var(--accent)', marginTop: 10, fontWeight: 500 }}>
                  考核周期：{weekStart} 至 {weekEnd}
                </div>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 20 }}>
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>驾驶员姓名</div>
                  <div style={{ fontSize: 15, fontWeight: 600 }}>{driver.name}</div>
                </div>
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>工号</div>
                  <div style={{ fontSize: 15, fontWeight: 600 }}>{driver.employeeId}</div>
                </div>
                {fleetName && (
                  <div>
                    <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>所属车队</div>
                    <div style={{ fontSize: 15, fontWeight: 600 }}>{fleetName}</div>
                  </div>
                )}
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>所属线路</div>
                  <div style={{ fontSize: 15, fontWeight: 600 }}>{route?.name || '-'}</div>
                </div>
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>联系电话</div>
                  <div style={{ fontSize: 15, fontWeight: 600 }}>{driver.phone}</div>
                </div>
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>面谈日期</div>
                  <div style={{ fontSize: 15, fontWeight: 600 }}>{interviewDate.replace(/-/g, ' / ')}</div>
                </div>
                <div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 4 }}>下次观察日期</div>
                  <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--accent)' }}>{nextReviewDate.replace(/-/g, ' / ')}</div>
                </div>
              </div>

              <div style={{ marginBottom: 20 }}>
                <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10, color: 'var(--text-secondary)' }}>
                  本周绩效概览
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10 }}>
                  <div style={{ background: 'var(--bg-primary)', padding: 12, borderRadius: 8, textAlign: 'center' }}>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>准点率</div>
                    <div style={{ fontSize: 18, fontWeight: 700, marginTop: 4, color: performance.onTimeRate >= 90 ? 'var(--success)' : 'var(--warning)' }}>
                      {performance.onTimeRate}%
                    </div>
                  </div>
                  <div style={{ background: 'var(--bg-primary)', padding: 12, borderRadius: 8, textAlign: 'center' }}>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>线路偏离</div>
                    <div style={{ fontSize: 18, fontWeight: 700, marginTop: 4, color: performance.deviationCount >= 5 ? 'var(--danger)' : 'var(--text-primary)' }}>
                      {performance.deviationCount}次
                    </div>
                  </div>
                  <div style={{ background: 'var(--bg-primary)', padding: 12, borderRadius: 8, textAlign: 'center' }}>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>急停/转弯</div>
                    <div style={{ fontSize: 18, fontWeight: 700, marginTop: 4, color: (performance.suddenBrakeCount + performance.suddenTurnCount) >= 8 ? 'var(--danger)' : 'var(--text-primary)' }}>
                      {performance.suddenBrakeCount + performance.suddenTurnCount}次
                    </div>
                  </div>
                  <div style={{ background: 'var(--bg-primary)', padding: 12, borderRadius: 8, textAlign: 'center' }}>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>GPS空白</div>
                    <div style={{ fontSize: 18, fontWeight: 700, marginTop: 4, color: performance.gpsBlankMinutes >= 20 ? 'var(--warning)' : 'var(--text-primary)' }}>
                      {performance.gpsBlankMinutes}分
                    </div>
                  </div>
                </div>
              </div>

              <div style={{ marginBottom: 20 }}>
                <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10, color: 'var(--text-secondary)' }}>
                  需整改问题项 ({selectedAnomalies.length}项)
                </div>
                <div style={{ background: 'var(--bg-primary)', borderRadius: 8, overflow: 'hidden' }}>
                  {selectedAnomalies.length === 0 ? (
                    <div style={{ padding: 16, textAlign: 'center', color: 'var(--text-muted)', fontSize: 13 }}>
                      未选择任何问题项
                    </div>
                  ) : (
                    selectedAnomalies.map((a, idx) => (
                      <div key={a.id} style={{ padding: 12, borderBottom: idx < selectedAnomalies.length - 1 ? '1px solid var(--border)' : 'none', display: 'flex', gap: 12 }}>
                        <div style={{
                          width: 26, height: 26, borderRadius: 6, flexShrink: 0,
                          background: `${ANOMALY_COLORS[a.type]}25`, color: ANOMALY_COLORS[a.type],
                          display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13
                        }}>
                          {ANOMALY_ICONS[a.type]}
                        </div>
                        <div style={{ flex: 1 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                            <span style={{ fontWeight: 600, color: ANOMALY_COLORS[a.type], fontSize: 13 }}>
                              {ANOMALY_LABELS[a.type]}
                            </span>
                            <span className={`badge ${a.severity === 'high' ? 'badge-red' : a.severity === 'medium' ? 'badge-yellow' : 'badge-gray'}`} style={{ fontSize: 10 }}>
                              {a.severity === 'high' ? '高危' : a.severity === 'medium' ? '中危' : '低危'}
                            </span>
                          </div>
                          <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 4 }}>
                            {a.date.replace(/-/g, '/')} {a.time} · {a.locationName}
                          </div>
                          <div style={{ fontSize: 12, color: 'var(--text-secondary)', marginTop: 4 }}>
                            {a.description}
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>

              <div style={{ marginBottom: 20 }}>
                <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10, color: 'var(--text-secondary)' }}>
                  改进要求
                </div>
                <div style={{ background: 'var(--bg-primary)', padding: 14, borderRadius: 8, fontSize: 13, lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
                  {improvementRequirements || '（未填写）'}
                </div>
              </div>

              {notes && (
                <div style={{ marginBottom: 20 }}>
                  <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10, color: 'var(--text-secondary)' }}>
                    主管备注
                  </div>
                  <div style={{ background: 'var(--bg-primary)', padding: 14, borderRadius: 8, fontSize: 13, lineHeight: 1.8, whiteSpace: 'pre-wrap' }}>
                    {notes}
                  </div>
                </div>
              )}

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, paddingTop: 24, borderTop: '1px solid var(--border)' }}>
                <div style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 30 }}>驾驶员签字确认</div>
                  <div style={{ borderBottom: '1px solid var(--border-light)', paddingBottom: 8 }}>&nbsp;</div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 6 }}>日期：____________</div>
                </div>
                <div style={{ textAlign: 'center' }}>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 30 }}>面谈主管签字</div>
                  <div style={{ borderBottom: '1px solid var(--border-light)', paddingBottom: 8, fontWeight: 500 }}>{supervisor}</div>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 6 }}>日期：{interviewDate.replace(/-/g, ' / ')}</div>
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="modal-footer">
          {!showGenerated ? (
            <>
              <button className="btn btn-outline" onClick={onClose}>取消</button>
              <button
                className="btn btn-primary"
                onClick={handleGenerate}
                disabled={selectedAnomalyIds.size === 0}
                style={selectedAnomalyIds.size === 0 ? { opacity: 0.5, cursor: 'not-allowed' } : {}}
              >
                生成面谈记录
              </button>
            </>
          ) : (
            <>
              <button className="btn btn-outline" onClick={() => setShowGenerated(false)}>返回编辑</button>
              <button className="btn btn-secondary" onClick={handlePrint}>🖨️ 打印记录</button>
              <button className="btn btn-primary" onClick={handleSaveAndClose}>
                {onSave ? '💾 保存并完成' : '✓ 确认完成'}
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}

export default InterviewModal
